---
layer3_interfaces:
 - { interface: 'Loopback0', ip_address: '10.1.30.2/32', description: 'Loopback0 VTEP' }
 - { interface: 'Ethernet1', ip_address: '10.1.20.10/30', description: 'Spine1' }
 - { interface: 'Ethernet2', ip_address: '10.1.20.14/30', description: 'Spine2' }
 - { interface: 'Ethernet3', ip_address: '10.1.10.2/30', description: 'Leaf1' }

layer2_interfaces:
 - { interface: 'Ethernet4', mode: 'access', vlan: '100', description: 'endhost2' }

bgp:
 as: "65021"
 router_id: "10.1.20.10"
 neighbours:
  - { peer_ip: '10.1.20.9', remote_as: '65020', description: 'Spine1' }
  - { peer_ip: '10.1.20.13', remote_as: '65020', description: 'Spine2' }
  - { peer_ip: '10.1.10.1', remote_as: '65021', description: 'Leaf1' }

