---
layer3_interfaces:
 - { interface: 'Ethernet1', ip_address: '10.1.20.10/30', description: 'Spine1' }
 - { interface: 'Ethernet2', ip_address: '10.1.20.14/30', description: 'Spine2' }

bgp:
 as: "65021"
 router_id: "10.1.20.10"
 neighbours:
  - { peer_ip: '10.1.20.9', remote_as: '65020', description: 'Spine1' }
  - { peer_ip: '10.1.20.13', remote_as: '65020', description: 'Spine2' }

