---
layer3_interfaces:
 - { interface: 'Loopback0', ip_address: '10.1.30.2/32', description: 'Loopback0 VTEP' }
 - { interface: 'Ethernet1', ip_address: '10.1.20.10/30', description: 'Spine1' }
 - { interface: 'Ethernet2', ip_address: '10.1.20.14/30', description: 'Spine2' }

layer2_interfaces:
 - { interface: 'Ethernet4', mode: 'access', vlan: '100', description: 'endhost2' }
 - { interface: 'Ethernet5', mode: 'access', vlan: '200', description: 'endhost2-app' }
 - { interface: 'Ethernet6', mode: 'access', vlan: '300', description: 'endhost2-db' }
 - { interface: 'Ethernet7', mode: 'access', vlan: '301', description: 'endhost2-db_rac' }


bgp:
 as: "65021"
 router_id: "10.1.20.10"
 neighbours:
  - { peer_ip: '10.1.20.9', remote_as: '65020', description: 'Spine1' }
  - { peer_ip: '10.1.20.13', remote_as: '65020', description: 'Spine2' }

