---
layer3_interfaces:
 - { interface: 'Ethernet1', ip_address: '10.1.20.2/30', description: 'Spine1' }
 - { interface: 'Ethernet2', ip_address: '10.1.20.6/30', description: 'Spine2' }

bgp:
 as: "65021"
 router_id: "10.1.20.2"
 neighbours:
  - { peer_ip: '10.1.20.1', remote_as: '65020', description: 'Spine1' }
  - { peer_ip: '10.1.20.5', remote_as: '65020', description: 'Spine2' }

