---
layer3_interfaces:
 - { interface: 'Loopback0', ip_address: '10.1.30.1/32', description: 'Loopback0 VTEP' }
 - { interface: 'Ethernet1', ip_address: '10.1.20.2/30', description: 'Spine1' }
 - { interface: 'Ethernet2', ip_address: '10.1.20.6/30', description: 'Spine2' }
 - { interface: 'Ethernet3', ip_address: '10.1.10.1/30', description: 'Leaf2' }

layer2_interfaces:
 - { interface: 'Ethernet4', mode: 'access', vlan: '100', description: 'endhost1' }

bgp:
 as: "65021"
 router_id: "10.1.20.2"
 neighbours:
  - { peer_ip: '10.1.20.1', remote_as: '65020', description: 'Spine1' }
  - { peer_ip: '10.1.20.5', remote_as: '65020', description: 'Spine2' }
  - { peer_ip: '10.1.10.2', remote_as: '65021', description: 'Leaf2' }

