---
layer3_interfaces:
 - { interface: 'Port-Channel1', ip_address: '10.1.20.9/30' }
 - { interface: 'GigabitEthernet2', ip_address: '10.1.20.2/30' }
 - { interface: 'GigabitEthernet5', ip_address: '10.1.20.17/30' }

port_channel_members:
 - { interface: 'GigabitEthernet3', channel_group: '1' }
 - { interface: 'GigabitEthernet4', channel_group: '1' }

bgp:
 as: "65020"
 router_id: "10.1.20.17"
 neighbours:
  - { peer_ip: '10.1.20.1', remote_as: '65001' }
  - { peer_ip: '10.1.20.10', remote_as: '65020' }
  - { peer_ip: '10.1.20.18', remote_as: '65021' }

