---
layer3_interfaces:
 - { interface: 'Port-Channel1', ip_address: '10.1.20.10/30' }
 - { interface: 'GigabitEthernet2', ip_address: '10.1.20.6/30' }
 - { interface: 'GigabitEthernet5', ip_address: '10.1.20.21/30' }

port_channel_members:
 - { interface: 'GigabitEthernet3', channel_group: '1' }
 - { interface: 'GigabitEthernet4', channel_group: '1' }

bgp:
 as: "65020"
 router_id: "10.1.20.6"
 neighbours:
  - { peer_ip: '10.1.20.5', remote_as: '65002' }
  - { peer_ip: '10.1.20.9', remote_as: '65020' }
  - { peer_ip: '10.1.20.22', remote_as: '65021' }

